apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: n1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodeport: 32222
  selector:
    app: nginx
  type: NodePort
