---
apiVersion: v1
kind: Node
metadata:
  name: worker-1
  labels:
    release: alpha
spec:
  taints: []

---
apiVersion: v1
kind: Node
metadata:
  name: worker-2
  labels:
    release: beta
spec:
  taints: []

---
apiVersion: v1
kind: Node
metadata:
  name: worker-3
  labels:
    release: stable
spec:
  taints: []

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n4
  name: app-1
  labels:
    name: app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-1
  template:
    metadata:
      labels:
        name: app-1
        env: dev
        app: front-end
        lang: javascript
        release: beta
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: release
                operator: In
                values:
                - beta
      containers:
        - image: busybox
          name: busybox
          args:
            - sleep
            - "1000000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n4
  name: app-2
  labels:
    name: app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-2
  template:
    metadata:
      labels:
        name: app-2
        env: dev
        app: back-end
        lang: python
        release: alpha
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: release
                operator: In
                values:
                - alpha
      containers:
        - image: busybox
          name: busybox
          args:
            - sleep
            - "1000000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n4
  name: app-3
  labels:
    name: app-3
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-3
  template:
    metadata:
      labels:
        name: app-3
        env: prod
        app: front-end
        lang: javascript
        release: stable
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: release
                operator: In
                values:
                - stable
      containers:
        - image: busybox
          name: busybox
          args:
            - sleep
            - "1000000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n4
  name: app-4
  labels:
    name: app-4
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-4
  template:
    metadata:
      labels:
        name: app-4
        env: prod
        app: front-end
        lang: javascript
        release: stable
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: release
                operator: In
                values:
                - stable
      containers:
        - image: busybox
          name: busybox
          args:
            - sleep
            - "1000000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n4
  name: app-5
  labels:
    name: app-5
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-5
  template:
    metadata:
      labels:
        name: app-5
        env: prod
        app: back-end
        lang: php
        release: stable
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: release
                operator: In
                values:
                - stable
      containers:
        - image: busybox
          name: busybox
          args:
            - sleep
            - "1000000"
