---
apiVersion: v1
kind: Pod
metadata:
  name: app-1
  namespace: n4
  labels:
    env: dev
    app: front-end
    lang: javascript
spec:
  containers:
    - image: ubuntu
      name: angular-font

---
apiVersion: v1
kind: Pod
metadata:
  name: app-2
  namespace: n4
  labels:
    env: dev
    app: back-end
    lang: python
spec:
  containers:
    - image: python
      name: python-back-end

---
apiVersion: v1
kind: Pod
metadata:
  name: app-3
  namespace: n4
  labels:
    env: prod
    app: front-end
    lang: javascript
spec:
  containers:
    - image: ubuntu
      name: angular-font

---
apiVersion: v1
kind: Pod
metadata:
  name: app-4
  namespace: n4
  labels:
    env: prod
    app: front-end
    lang: javascript
spec:
  containers:
    - image: ubuntu
      name: react-front

---
apiVersion: v1
kind: Pod
metadata:
  name: app-5
  namespace: n4
  labels:
    env: prod
    app: back-end
    lang: php
spec:
  containers:
    - image: php:7.1
      name: php-api
