---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n4
  name: nginx-deployment
  labels:
    name: app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-1
  template:
    metadata:
      labels:
        name: app-1
        env: dev
        app: front-end
        lang: javascript
        release: beta
    spec:
      containers:
        - image: busybox
          name: busybox
          args:
            - sleep
            - "1000000"

---
apiVersion: v1
kind: Pod
metadata:
  name: app-2
  namespace: n4
  labels:
    env: dev
    app: back-end
    lang: python
    release: beta
spec:
  containers:
    - image: busybox
      name: busybox
      args:
        - sleep
        - "1000000"

---
apiVersion: v1
kind: Pod
metadata:
  name: app-3
  namespace: n4
  labels:
    env: prod
    app: front-end
    lang: javascript
    release: stable
spec:
  containers:
    - image: busybox
      name: busybox
      args:
        - sleep
        - "1000000"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-4
  namespace: n4
  labels:
    env: prod
    app: front-end
    lang: javascript
    release: stable
spec:
  containers:
    - image: busybox
      name: busybox
      args:
        - sleep
        - "1000000"

---
apiVersion: v1
kind: Pod
metadata:
  name: app-5
  namespace: n4
  labels:
    env: prod
    app: back-end
    lang: php
    release: stable
spec:
  containers:
    - image: busybox
      name: busybox
      args:
        - sleep
        - "1000000"
