apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: exo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: "wordpress"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
          ports:
          - containerPort: 3306
            protocol: TCP
