apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
  namespace: exo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: "localhost"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              value: "1234"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
            - name: WORDPRESS_TABLE_PREFIX
              value: "wp_"
          ports:
            - containerPort: 80
              protocol: TCP
