---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
  namespace: ex2
data:
  WORDPRESS_DB_HOST: mysql
  WORDPRESS_DB_USER: admin
  WORDPRESS_DB_PASSWORD: 1234
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_PREFIX: wp_
  MYSQL_DATABASE: wordpress
  MYSQL_USER: admin
  MYSQL_PASSWORD: 1234
  MYSQL_RANDOM_ROOT_PASSWORD: 1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: ex2
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: ex2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          envFrom:
            - configMapRef:
                name: wordpress-mysql
          ports:
            - containerPort: 3306
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: ex2
spec:
  ports:
    - nodePort: 30999
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
  namespace: ex2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          envFrom:
            - configMapRef:
                name: wordpress-mysql
          ports:
            - containerPort: 80
              protocol: TCP
